version: '3.8'
services:
  dotnet-app:
    container_name: dotnet-devcontainer-scaffold
    build: .
    volumes:
      - ../:/app:cached
    ports:
      - 8080:8080
    command: /bin/sh -c "while sleep 1000; do :; done"
    